services:
  db:
    image: postgres
    container_name: recipe_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: recipe_db
    ports:
      - "5432:5432"
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
