version: "3"
services:
  db:
    image: postgres
    container_name: recipe_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: recipe_db
    ports:
      - "5432:5432"
